name: Deploy to a Docker
on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aqib2110/my-codely-app:${{ github.sha }}

      - name: Deploy to VM
        env:
          GITHUB_SHA: ${{ github.sha }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.48.129.114 "
            docker rm -f my-codely-app || true
            docker run -d \
            --name my-codely-app \
            -p 3000:3000 \
            -p 8080:8080 \
            -p 3001:3001 \
            -p 9000:9000 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e DATABASE_URL='${DATABASE_URL}' \
            -e NEXTAUTH_SECRET='${NEXTAUTH_SECRET}' \
            -e NEXTAUTH_URL='${NEXTAUTH_URL}' \
            --restart=always \
            aqib2110/my-codely-app:${GITHUB_SHA}
          "
          rm -f ~/ssh_key
